In [5]:
import pandas as pd
import numpy as np

In [6]:
from sklearn.linear_model import LogisticRegression
data= pd.read_csv('covid 19 dataset.csv')
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_size = int(len(data) * ratio)
    test_indices = shuffled[:test_size]
    train_indices = shuffled[test_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [7]:
np.random.permutation(8)
train, test = data_split(data, 0.2)

In [8]:
train

,country,"creatine kinase-MB, U/L","D-dimer, mg/L","Lactate dehydrogenase, U/L",ICU/NN-ICU
18,china,32,975,497,1
10,china,28,731,595,1
125,china,14,141,253,0
51,china,10,152,276,0
11,china,14,646,400,1
...,...,...,...,...,...
71,china,10,250,222,0
106,china,10,192,206,0
14,china,20,1028,319,1
92,china,10,240,244,0
102,china,14,278,202,0

In [9]:
test

,country,"creatine kinase-MB, U/L","D-dimer, mg/L","Lactate dehydrogenase, U/L",ICU/NN-ICU
89,china,13,149,198,0
105,china,14,232,195,0
12,china,23,823,441,1
26,china,35,1131,373,1
64,china,11,227,270,0
67,china,11,221,246,0
65,china,12,129,268,0
117,china,13,213,215,0
108,china,10,199,186,0
73,china,14,181,257,0
85,china,11,172,239,0
45,china,11,141,275,0
76,china,12,256,190,0
68,china,11,214,248,0
31,china,12,524,548,1
42,china,14,208,270,0
27,china,35,712,570,1
19,china,28,679,467,1
86,china,14,219,267,0
56,china,14,284,284,0
109,china,10,111,178,0
4,china,16,1025,586,1
111,china,13,130,272,0
36,china,14,196,193,0
104,china,12,237,255,0
136,china,10,164,248,0
16,china,18,544,493,1

In [10]:
X_train = train[['creatine kinase-MB, U/L', 'D-dimer, mg/L', 'Lactate dehydrogenase, U/L']].to_numpy()
X_test = test[['creatine kinase-MB, U/L', 'D-dimer, mg/L', 'Lactate dehydrogenase, U/L']].to_numpy()

In [11]:
Y_train = train[['ICU/NN-ICU']].to_numpy().reshape(111 ,)
Y_test = test[['ICU/NN-ICU']].to_numpy().reshape(27 ,)

In [12]:
X_train

array([[  32,  975,  497],
       [  28,  731,  595],
       [  14,  141,  253],
       [  10,  152,  276],
       [  14,  646,  400],
       [  14,  131,  232],
       [  10,  158,  174],
       [  13,  261,  248],
       [  10,  174,  289],
       [  12,  154,  209],
       [  19, 1156,  384],
       [  13,  130,  213],
       [  14,  156,  199],
       [  13,  279,  172],
       [  27, 1091,  488],
       [  10,  284,  182],
       [  13,  167,  225],
       [  14,  109,  179],
       [  13,  188,  291],
       [  13,  576,  587],
       [  14,  275,  201],
       [  10,  148,  261],
       [  17,  944,  425],
       [  11,  234,  176],
       [  13,  124,  289],
       [  12,  193,  283],
       [  11,  163,  253],
       [  24,  750,  381],
       [  10,  268,  257],
       [  14,  144,  252],
       [  31,  664,  511],
       [  13, 1029,  477],
       [  11,  101,  230],
       [  20,  751,  429],
       [  12,  174,  222],
       [  12,  104,  231],
       [  22,  737,  560],
       [  11,  102,  219],
       [  11,  207,  286],
       [  10,  282,  215],
       [  22,  739,  598],
       [  13,  151,  189],
       [  12,  131,  247],
       [  10,  232,  208],
       [  27,  780,  552],
       [  27, 1276,  542],
       [  10,  207,  183],
       [  30,  975,  494],
       [  10,  167,  269],
       [  12,  187,  184],
       [  11,  249,  171],
       [  10,  263,  238],
       [  10,  130,  240],
       [  35,  686,  407],
       [  26,  982,  336],
       [  10,  223,  286],
       [  24,  719,  439],
       [  23,  652,  473],
       [  11,  256,  218],
       [  12,  242,  218],
       [  10,  265,  283],
       [  17,  773,  312],
       [  12,  181,  197],
       [  14,  128,  275],
       [  10,  123,  224],
       [  14,  231,  274],
       [  11,  137,  260],
       [  14,  133,  223],
       [  11,  207,  246],
       [  10,  172,  283],
       [  13,  179,  184],
       [  13,  114,  213],
       [  13,  248,  248],
       [  13,  127,  259],
       [  14,  191,  202],
       [  11,  117,  270],
       [  10,  193,  259],
       [  11,  157,  212],
       [  11,  128,  198],
       [  12,  263,  279],
       [  14,  138,  180],
       [  14,  138,  231],
       [  14,  225,  269],
       [  12,  247,  259],
       [  20, 1285,  467],
       [  14,  235,  217],
       [  10,  242,  186],
       [  10,  158,  186],
       [  12,  216,  193],
       [  12,  105,  206],
       [  19,  429,  393],
       [  10,  246,  214],
       [  13,  274,  217],
       [  31,  843,  597],
       [  10,  179,  279],
       [  34,  600,  573],
       [  32, 1036,  399],
       [  28, 1038,  430],
       [  12,  128,  238],
       [  11,  179,  230],
       [  11,  142,  290],
       [  12,  251,  204],
       [  10,  200,  252],
       [  13,  187,  199],
       [  14,  240,  280],
       [  22,  523,  511],
       [  10,  250,  222],
       [  10,  192,  206],
       [  20, 1028,  319],
       [  10,  240,  244],
       [  14,  278,  202]], dtype=int64)

In [13]:
Y_train

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0], dtype=int64)

In [14]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier

In [16]:
y_pred=clf.predict(X_test)

In [17]:
accuracy_score(Y_test,y_pred)

1.0

In [18]:
a=int(input("enter your creatine kinase-MB value U/L:- "))
b=int(input("enter your D-dimer vale in gm/L:-"))
c=int(input("enter your Lactate dehydrogenase value inU/L:- "))

enter your creatine kinase-MB value U/L:- 10
enter your D-dimer vale in gm/L:-12
enter your Lactate dehydrogenase value inU/L:- 12

In [19]:
input = [a,b,c]

In [20]:
infProb=clf.predict_proba([input])[0][1]

In [21]:
infProb=round(infProb)

In [22]:
if(infProb==1):
    print('you condition is critical')
else:
    print("you are out of danger but adviced to stay at home")

you are out of danger but adviced to stay at home